#Listado de anotacion del curso 5 "productivity tools" Unix

#1. En el terminal puedes escribir "pwd" para saber tu ubicacion actual
#2. Listado para navegar el file system 

#You can either type out the home directory (/Users/rafa) 
# or use ~ as the nickname for the home directory (~).
# ls #list dir content
# mkdir folder_name #create directory called "folder_name"
# rmdir folder_name  #remove an empty directory as long as it is empty
# rm -r folder_name  #remove dir that is not empty, "r" stands for recursive
# cd: change dir
../ # two dots represents parent dir
  . # single dot represents current working dir 
# cd ~/projects # concatenate with forward slashes
# cd ../.. # change to two parent layer beyond
# cd -  # whatever dir you were before
#  cd  # return to the home dir

#3. Para movir y remover se usan:
# mv path-to-file path-to-destination-directory 
# ejemplo (mv ./Borrar_2.txt  ./proyects)
# rm filename-1 filename-2 filename-3

#4. Para ver un documento usar "less"
# Ejemplo less Notas.txt      (para salir usar q)

#5. Ejercicio

########### In terminal ###########
#cd ~    # move to home directory
#mkdir projects    # make a new directory called projects
#cd projects    # move to ~/projects directory
#mkdir murders    # make new directory called murders inside of projects
#cd murders    # move to ~/projects/murders/
#mkdir data rda    # make two new directories, one is data the other is rda folder
#ls    # to check if we indeed have one data folder and one rda folder
#pwd    # check the current working directory
#mkdir figs    # make a directory called figs to store figures

########## In RStudio ########
# pick existing directory as new project
#getwd()    # to confirm current working directory
#save()    # save into .rda file, .RData is also fine but less preferred
#ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"

#6. Using Git hub from our terminal

#Recap: there are four stages: working directory, staging area, local repository, and upstream repository
#Clone an existing upstream repository (copy repo url from clone button, and type "git clone <url>"), and all three local stages are the same as upstream remote.
#The working directory is the same as the working directory in Rstudio. When we edit files we only change the files in this place.
#git status: tells how the files in the working directory are related to the files in other stages
#edits in the staging area are not tracked by the version control system by default - we add a file to the staging area by git add command
#git commit: to commit files from the staging area to local repository, we need to add a message stating what we are doing by git commit -m "something"
#git log: keeps track of all the changes we have made to the local repository
#git push: allows moving from the local repository to upstream repository, only if you have the permission (e.g. if it is yours)
#git fetch: update local repository to  be like the upstream repository, from upstream to local
#git merge: make the updated local sync with the working directory and staging area
#To change everything in one shot (from upstream to working dir), use git pull (equivalent to combining git fetch + git merge)

#7. Creating a github from our terminal